package ense600comp603project1;

import javax.swing.JPanel;

public class ViewJFrame extends javax.swing.JFrame {
    //MVC View
    
    public ViewJFrame() {
        initComponents();
    }
    
    private void showPanelPlease(JPanel panel, JPanel parent)
    {
//        JPanelScreens.removeAll();
//        JPanelScreens.add(JPanel1_MainMenu);
//        JPanelScreens.repaint();
//        JPanelScreens.revalidate();
        parent.removeAll();
        parent.add(panel);
        parent.repaint();
        parent.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelScreens = new javax.swing.JPanel();
        JPanel0_Settings = new javax.swing.JPanel();
        chkboxEnableMusic = new javax.swing.JCheckBox();
        labelPickQuiz = new javax.swing.JLabel();
        comboPickQuiz = new javax.swing.JComboBox<>();
        btn1_MainMenu = new javax.swing.JButton();
        JPanel1_MainMenu = new javax.swing.JPanel();
        btnMakeQuiz = new javax.swing.JButton();
        btnStartQuiz = new javax.swing.JButton();
        btnViewScore = new javax.swing.JButton();
        btnSettings = new javax.swing.JButton();
        JPanel2_Q = new javax.swing.JPanel();
        labelQuestion = new javax.swing.JLabel();
        JPanelZ_Q_Mini = new javax.swing.JPanel();
        JPanelA_Q_Mini_Question = new javax.swing.JPanel();
        btnOptionB = new javax.swing.JButton();
        btnOptionC = new javax.swing.JButton();
        btnOptionD = new javax.swing.JButton();
        btnOptionA = new javax.swing.JButton();
        JPanelB_Q_Mini_Answer = new javax.swing.JPanel();
        labelAnswer = new javax.swing.JLabel();
        btnNextQuestion = new javax.swing.JButton();
        JPanel3_FinalResult = new javax.swing.JPanel();
        labelResult = new javax.swing.JLabel();
        labelEnterName = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        fieldEnterName = new javax.swing.JTextField();
        JPanel4_HighScores = new javax.swing.JPanel();
        listHighScores = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelYourScore = new javax.swing.JLabel();
        btnLeaveHighscores = new javax.swing.JButton();
        fieldYourScore = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelScreens.setLayout(new java.awt.CardLayout());

        chkboxEnableMusic.setText("Enable Music?");
        chkboxEnableMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkboxEnableMusicActionPerformed(evt);
            }
        });

        labelPickQuiz.setText("Pick a quiz");

        comboPickQuiz.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quiz 1", "Quiz 2" }));

        btn1_MainMenu.setText("Main Menu");
        btn1_MainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1_MainMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel0_SettingsLayout = new javax.swing.GroupLayout(JPanel0_Settings);
        JPanel0_Settings.setLayout(JPanel0_SettingsLayout);
        JPanel0_SettingsLayout.setHorizontalGroup(
            JPanel0_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel0_SettingsLayout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addGroup(JPanel0_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(chkboxEnableMusic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboPickQuiz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelPickQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1_MainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(231, Short.MAX_VALUE))
        );
        JPanel0_SettingsLayout.setVerticalGroup(
            JPanel0_SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel0_SettingsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(chkboxEnableMusic)
                .addGap(54, 54, 54)
                .addComponent(labelPickQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboPickQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn1_MainMenu)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        JPanelScreens.add(JPanel0_Settings, "card6");

        btnMakeQuiz.setText("Make a Quiz");
        btnMakeQuiz.setEnabled(false);

        btnStartQuiz.setText("Start Quiz");
        btnStartQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartQuizActionPerformed(evt);
            }
        });

        btnViewScore.setText("View Score");
        btnViewScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewScoreActionPerformed(evt);
            }
        });

        btnSettings.setText("Settings");
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel1_MainMenuLayout = new javax.swing.GroupLayout(JPanel1_MainMenu);
        JPanel1_MainMenu.setLayout(JPanel1_MainMenuLayout);
        JPanel1_MainMenuLayout.setHorizontalGroup(
            JPanel1_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1_MainMenuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(JPanel1_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStartQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMakeQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewScore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        JPanel1_MainMenuLayout.setVerticalGroup(
            JPanel1_MainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1_MainMenuLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btnStartQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMakeQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSettings)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        JPanelScreens.add(JPanel1_MainMenu, "card2");

        labelQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelQuestion.setText("Where are you right now?");

        JPanelZ_Q_Mini.setLayout(new java.awt.CardLayout());

        btnOptionB.setText("There");
        btnOptionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionBActionPerformed(evt);
            }
        });

        btnOptionC.setText("Somewhere Else");
        btnOptionC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionCActionPerformed(evt);
            }
        });

        btnOptionD.setText("14th St, Santa Monica, USA");
        btnOptionD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionDActionPerformed(evt);
            }
        });

        btnOptionA.setText("Here");
        btnOptionA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOptionAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelA_Q_Mini_QuestionLayout = new javax.swing.GroupLayout(JPanelA_Q_Mini_Question);
        JPanelA_Q_Mini_Question.setLayout(JPanelA_Q_Mini_QuestionLayout);
        JPanelA_Q_Mini_QuestionLayout.setHorizontalGroup(
            JPanelA_Q_Mini_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelA_Q_Mini_QuestionLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(JPanelA_Q_Mini_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelA_Q_Mini_QuestionLayout.createSequentialGroup()
                        .addComponent(btnOptionA, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnOptionB, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelA_Q_Mini_QuestionLayout.createSequentialGroup()
                        .addComponent(btnOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btnOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        JPanelA_Q_Mini_QuestionLayout.setVerticalGroup(
            JPanelA_Q_Mini_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelA_Q_Mini_QuestionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(JPanelA_Q_Mini_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOptionA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOptionB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(JPanelA_Q_Mini_QuestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOptionC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOptionD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        JPanelZ_Q_Mini.add(JPanelA_Q_Mini_Question, "card4");

        labelAnswer.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        labelAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAnswer.setText("WRONG");

        btnNextQuestion.setText("next question");
        btnNextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelB_Q_Mini_AnswerLayout = new javax.swing.GroupLayout(JPanelB_Q_Mini_Answer);
        JPanelB_Q_Mini_Answer.setLayout(JPanelB_Q_Mini_AnswerLayout);
        JPanelB_Q_Mini_AnswerLayout.setHorizontalGroup(
            JPanelB_Q_Mini_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelB_Q_Mini_AnswerLayout.createSequentialGroup()
                .addGroup(JPanelB_Q_Mini_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelB_Q_Mini_AnswerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelB_Q_Mini_AnswerLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnNextQuestion)))
                .addGap(326, 326, 326))
        );
        JPanelB_Q_Mini_AnswerLayout.setVerticalGroup(
            JPanelB_Q_Mini_AnswerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelB_Q_Mini_AnswerLayout.createSequentialGroup()
                .addComponent(labelAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNextQuestion)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        JPanelZ_Q_Mini.add(JPanelB_Q_Mini_Answer, "card4");

        javax.swing.GroupLayout JPanel2_QLayout = new javax.swing.GroupLayout(JPanel2_Q);
        JPanel2_Q.setLayout(JPanel2_QLayout);
        JPanel2_QLayout.setHorizontalGroup(
            JPanel2_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2_QLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(JPanel2_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelZ_Q_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        JPanel2_QLayout.setVerticalGroup(
            JPanel2_QLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2_QLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(JPanelZ_Q_Mini, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        JPanelScreens.add(JPanel2_Q, "card3");

        labelResult.setFont(new java.awt.Font("Segoe UI", 0, 100)); // NOI18N
        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResult.setText("You Lose");

        labelEnterName.setText("Please enter your name:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel3_FinalResultLayout = new javax.swing.GroupLayout(JPanel3_FinalResult);
        JPanel3_FinalResult.setLayout(JPanel3_FinalResultLayout);
        JPanel3_FinalResultLayout.setHorizontalGroup(
            JPanel3_FinalResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel3_FinalResultLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(JPanel3_FinalResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel3_FinalResultLayout.createSequentialGroup()
                        .addComponent(labelEnterName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubmit))
                    .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        JPanel3_FinalResultLayout.setVerticalGroup(
            JPanel3_FinalResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel3_FinalResultLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(JPanel3_FinalResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldEnterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEnterName)
                    .addComponent(btnSubmit))
                .addContainerGap())
        );

        JPanelScreens.add(JPanel3_FinalResult, "card6");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(8);
        jTextArea1.setText("1. Fin\t6000\n2. Bean\t3000\n3. Joe\t2000\n...\n...\n97. Example\t123\n98. Example\t123\n99. Bruh\t-1");
        listHighScores.setViewportView(jTextArea1);

        labelYourScore.setText("Your Score:");

        btnLeaveHighscores.setText("Leave Highscores");
        btnLeaveHighscores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveHighscoresActionPerformed(evt);
            }
        });

        fieldYourScore.setText("???");
        fieldYourScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldYourScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel4_HighScoresLayout = new javax.swing.GroupLayout(JPanel4_HighScores);
        JPanel4_HighScores.setLayout(JPanel4_HighScoresLayout);
        JPanel4_HighScoresLayout.setHorizontalGroup(
            JPanel4_HighScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel4_HighScoresLayout.createSequentialGroup()
                .addGroup(JPanel4_HighScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel4_HighScoresLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(JPanel4_HighScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelYourScore)
                            .addComponent(listHighScores)
                            .addComponent(fieldYourScore, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanel4_HighScoresLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(btnLeaveHighscores, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        JPanel4_HighScoresLayout.setVerticalGroup(
            JPanel4_HighScoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel4_HighScoresLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(listHighScores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelYourScore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldYourScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnLeaveHighscores)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        JPanelScreens.add(JPanel4_HighScores, "card7");

        getContentPane().add(JPanelScreens, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnStartQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartQuizActionPerformed
        showPanelPlease(JPanelA_Q_Mini_Question,JPanelZ_Q_Mini);
        showPanelPlease(JPanel2_Q, JPanelScreens);
    }//GEN-LAST:event_btnStartQuizActionPerformed

    private void btnOptionAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionAActionPerformed
        showPanelPlease(JPanelB_Q_Mini_Answer,JPanelZ_Q_Mini);
    }//GEN-LAST:event_btnOptionAActionPerformed

    private void btnNextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextQuestionActionPerformed
        showPanelPlease(JPanel3_FinalResult,JPanelScreens);
    }//GEN-LAST:event_btnNextQuestionActionPerformed

    private void chkboxEnableMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkboxEnableMusicActionPerformed
        if(chkboxEnableMusic.isSelected())
        {
            //System.out.println("ACTIVE");
            MusicLoopThread m = new MusicLoopThread("resources/KevinMacleod.wav",10000); //every 10 seconds, loop music
            Thread musicThread = new Thread(m);
            //START MUSIC THREAD (must close at end of program)
            musicThread.start();
            //When checkbox enabled, disabling the option to turn off music because its funny
            //(and because implementing a proper option is hard)
            chkboxEnableMusic.setEnabled(false);
            chkboxEnableMusic.setToolTipText("\"It's not a bug, it's a feature\" - Albert Einstein");
        } else
        {
            //System.out.println("NAH NOT ACTIVE");
        }
    }//GEN-LAST:event_chkboxEnableMusicActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        showPanelPlease(JPanel4_HighScores,JPanelScreens);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btn1_MainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1_MainMenuActionPerformed
        showPanelPlease(JPanel1_MainMenu,JPanelScreens);
    }//GEN-LAST:event_btn1_MainMenuActionPerformed

    private void btnLeaveHighscoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveHighscoresActionPerformed
        showPanelPlease(JPanel1_MainMenu,JPanelScreens);
    }//GEN-LAST:event_btnLeaveHighscoresActionPerformed

    private void btnViewScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewScoreActionPerformed
        showPanelPlease(JPanel4_HighScores,JPanelScreens);
    }//GEN-LAST:event_btnViewScoreActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        showPanelPlease(JPanel0_Settings,JPanelScreens);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void fieldYourScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldYourScoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldYourScoreActionPerformed

    private void btnOptionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionBActionPerformed
        showPanelPlease(JPanelB_Q_Mini_Answer,JPanelZ_Q_Mini);
    }//GEN-LAST:event_btnOptionBActionPerformed

    private void btnOptionCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionCActionPerformed
        showPanelPlease(JPanelB_Q_Mini_Answer,JPanelZ_Q_Mini);
    }//GEN-LAST:event_btnOptionCActionPerformed

    private void btnOptionDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOptionDActionPerformed
        showPanelPlease(JPanelB_Q_Mini_Answer,JPanelZ_Q_Mini);
    }//GEN-LAST:event_btnOptionDActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel0_Settings;
    private javax.swing.JPanel JPanel1_MainMenu;
    private javax.swing.JPanel JPanel2_Q;
    private javax.swing.JPanel JPanel3_FinalResult;
    private javax.swing.JPanel JPanel4_HighScores;
    private javax.swing.JPanel JPanelA_Q_Mini_Question;
    private javax.swing.JPanel JPanelB_Q_Mini_Answer;
    private javax.swing.JPanel JPanelScreens;
    private javax.swing.JPanel JPanelZ_Q_Mini;
    private javax.swing.JButton btn1_MainMenu;
    private javax.swing.JButton btnLeaveHighscores;
    private javax.swing.JButton btnMakeQuiz;
    private javax.swing.JButton btnNextQuestion;
    private javax.swing.JButton btnOptionA;
    private javax.swing.JButton btnOptionB;
    private javax.swing.JButton btnOptionC;
    private javax.swing.JButton btnOptionD;
    private javax.swing.JButton btnSettings;
    private javax.swing.JButton btnStartQuiz;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewScore;
    private javax.swing.JCheckBox chkboxEnableMusic;
    private javax.swing.JComboBox<String> comboPickQuiz;
    private javax.swing.JTextField fieldEnterName;
    private javax.swing.JTextField fieldYourScore;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelAnswer;
    private javax.swing.JLabel labelEnterName;
    private javax.swing.JLabel labelPickQuiz;
    private javax.swing.JLabel labelQuestion;
    private javax.swing.JLabel labelResult;
    private javax.swing.JLabel labelYourScore;
    private javax.swing.JScrollPane listHighScores;
    // End of variables declaration//GEN-END:variables
}
